
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-10T19:19:05-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2848b812b806d08fc5ea3fb798ecd58d9853a07",
 "version": "0.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
