# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from nebius.api.nebius.iam.v1 import token_service_pb2 as nebius_dot_iam_dot_v1_dot_token__service__pb2


class IdentityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeToken = channel.unary_unary(
                '/nebius.iam.v1.IdentityService/ExchangeToken',
                request_serializer=nebius_dot_iam_dot_v1_dot_token__service__pb2.ExchangeTokenRequest.SerializeToString,
                response_deserializer=nebius_dot_iam_dot_v1_dot_token__service__pb2.CreateTokenResponse.FromString,
                )


class IdentityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExchangeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeToken,
                    request_deserializer=nebius_dot_iam_dot_v1_dot_token__service__pb2.ExchangeTokenRequest.FromString,
                    response_serializer=nebius_dot_iam_dot_v1_dot_token__service__pb2.CreateTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nebius.iam.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExchangeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nebius.iam.v1.IdentityService/ExchangeToken',
            nebius_dot_iam_dot_v1_dot_token__service__pb2.ExchangeTokenRequest.SerializeToString,
            nebius_dot_iam_dot_v1_dot_token__service__pb2.CreateTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
