# Generated by Django 3.2.12 on 2022-03-16 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djp_sepa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepamandate',
            name='mandate_id',
            field=models.CharField(default='-', max_length=35, validators=[django.core.validators.RegexValidator(regex="^[A-Z0-9+?/:().,'-]{1,35}$")], verbose_name='Mandate ID'),
            preserve_default=False,
        ),
    ]
