
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-10T04:57:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b08e57fc5361cbcec1888b9bf99e6eb9a7e6767",
 "version": "1.32.0.post0.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
