"""
Django settings for tracker project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

print(os.path.join(BASE_DIR, 'templates'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3o_@&oc0!@s%&x$ldq8g1^a95d62ws+b6iijhore42uk90r1s0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['1a03163033cb41b081e03a1cfe09181a.vfs.cloud9.us-east-1.amazonaws.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'time_tracker', #register new application
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware', #메세지 출력
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_REDIRECT_URL = 'dashboard'  # 로그인 후 리다이렉트할 URL
LOGIN_URL = '/login/' # 로그인 페이지 리디렉션 설정
AUTH_USER_MODEL = 'time_tracker.CustomUser'

ROOT_URLCONF = 'tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # templates 디렉토리 경로
        'APP_DIRS': True,  # 앱 내 templates 폴더 확인
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# AWS S3 설정 (여기에 본인의 값을 입력)
AWS_ACCESS_KEY_ID = "ASIAUBQBANIFFAJVNLLE"
AWS_SECRET_ACCESS_KEY = "N/YeGGxxDy7acLXUIDtPUk6EMkPVaFvtmefqja1F"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEOf//////////wEaCXVzLXdlc3QtMiJIMEYCIQCmTlnnok+0w7GFwDej/yKbdmZoXm+LOY/tkzd1y5CFhgIhAOiYHe3Pby+AfDrGGvPG4s3Nn59oTNy2QNeW8d6XitHWKrQCCDAQABoMMjc4MTAxMjU2NzE0IgzOcb37rY5jwG+ba2YqkQI+91h2X/1QhKALX1XX00foltDL2SdabOAgRKyzQCylnNpeaLP5Q2jQhvIwp6Z8EHV707vpUXkPEDap67GrDg708ezsyp0zV1eaRWOCUvMbSbuIpfZpdtcuzXG59Fd0VL06ZbuN0/Bo8C4LSh+laV3BBqHc+gR6+DzITG5W46W7+02f7M+X8FbAp9iEUgkkXgHQIJ4xZNsVql2bSUBY5wmMxtuieK5bF7RQyYTxGWLNp099yHS0KUkYtVrlhXdzYkBEzuZPPOPkExdz3h9094txwiBSW8pJBwTWEncIVtu8FPJpzFHKutn077JPCFp+5j3dJ1aHVWBei8AMWUf7ja03thc4NcjMzAL/7c2GkulXWzYw4PamvgY6nAHyIqeg4m51xYk8t/M7hQ/fSH7CXtQPm8EAp0DoFoIwmD9GK4N1roQtL+rwgMlTF58Yy9DPyEwx7j4wdypSgQifs4NQfSMpvgOF8JjX6m7fIK8jIm4A7oJUPr5sAAwkyyMVmKAkQn2ZLXG/BjZeGTjnVfvtcxzsQ8tfeHKfDT9l0txfxSJu00PCo1YQrtbOXJEHlzR/U3EQT8PhHKc="
AWS_STORAGE_BUCKET_NAME = "x24142816-s3bucket"  # 생성한 버킷 이름
AWS_S3_REGION_NAME = "us-east-1"  # 선택한 리전
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
# 파일 저장 설정
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
    'ContentDisposition': 'inline'
}

AWS_S3_FILE_OVERWRITE = False  # 동일한 파일명 업로드 시 덮어쓰기 방지
AWS_DEFAULT_ACL = None  # 기본적으로 private 상태 유지 (보안상 안전)
AWS_S3_ADDRESSING_STYLE = "path"

# AWS SNS 설정 
AWS_ACCESS_KEY_ID = "ASIAUBQBANIFFAJVNLLE"
AWS_SECRET_ACCESS_KEY = "N/YeGGxxDy7acLXUIDtPUk6EMkPVaFvtmefqja1F"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEOf//////////wEaCXVzLXdlc3QtMiJIMEYCIQCmTlnnok+0w7GFwDej/yKbdmZoXm+LOY/tkzd1y5CFhgIhAOiYHe3Pby+AfDrGGvPG4s3Nn59oTNy2QNeW8d6XitHWKrQCCDAQABoMMjc4MTAxMjU2NzE0IgzOcb37rY5jwG+ba2YqkQI+91h2X/1QhKALX1XX00foltDL2SdabOAgRKyzQCylnNpeaLP5Q2jQhvIwp6Z8EHV707vpUXkPEDap67GrDg708ezsyp0zV1eaRWOCUvMbSbuIpfZpdtcuzXG59Fd0VL06ZbuN0/Bo8C4LSh+laV3BBqHc+gR6+DzITG5W46W7+02f7M+X8FbAp9iEUgkkXgHQIJ4xZNsVql2bSUBY5wmMxtuieK5bF7RQyYTxGWLNp099yHS0KUkYtVrlhXdzYkBEzuZPPOPkExdz3h9094txwiBSW8pJBwTWEncIVtu8FPJpzFHKutn077JPCFp+5j3dJ1aHVWBei8AMWUf7ja03thc4NcjMzAL/7c2GkulXWzYw4PamvgY6nAHyIqeg4m51xYk8t/M7hQ/fSH7CXtQPm8EAp0DoFoIwmD9GK4N1roQtL+rwgMlTF58Yy9DPyEwx7j4wdypSgQifs4NQfSMpvgOF8JjX6m7fIK8jIm4A7oJUPr5sAAwkyyMVmKAkQn2ZLXG/BjZeGTjnVfvtcxzsQ8tfeHKfDT9l0txfxSJu00PCo1YQrtbOXJEHlzR/U3EQT8PhHKc="
AWS_REGION = "us-east-1"  # 사용 중인 리전
SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:278101256714:x24142816-notification"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://1a03163033cb41b081e03a1cfe09181a.vfs.cloud9.us-east-1.amazonaws.com',
]