# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nillion/permissions/v1/retrieve.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto

from ....payments.v1 import receipt as ___payments_v1_receipt__


@dataclass(eq=False, repr=False)
class RetrievePermissionsRequest(betterproto.Message):
    """
    A request to retrieve the permissions associated with a set of previously stored values.
    """

    signed_receipt: "___payments_v1_receipt__.SignedReceipt" = (
        betterproto.message_field(1)
    )
    """
    The receipt that proves this operation was paid for.
    
     The receipt must be for a `RetrievePermissions` operation.
    """
