# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.07.232704'

RELEASE_GIT_HEAD = '05c8023a27dd37c49163c0498bf98e3e3c1cb4b9'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.03.07.232704dev'
