
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-09T02:16:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "19fadf962d87a21e1d0edf8d72299e82f7611140",
 "version": "1.5.dev2510"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
