PROTOCOL_DEFAULT_TIMEOUT: int
PROTOCOL_DEFAULT_PORT: int
PROTOCOL_HEADER: bytes

MAX_CHANNELS: int

TYPE_METHOD: int
TYPE_HEADER: int
TYPE_BODY: int
TYPE_HEARTBEAT: int

FRAME_END: bytes

CLASS_CONNECTION: int
CLASS_CHANNEL: int
CLASS_EXCHANGE: int
CLASS_QUEUE: int
CLASS_BASIC: int
CLASS_TX: int
CLASS_CONFIRM: int

CONNECTION_START: int
CONNECTION_START_OK: int
CONNECTION_SECURE: int
CONNECTION_SECURE_OK: int
CONNECTION_TUNE: int
CONNECTION_TUNE_OK: int
CONNECTION_OPEN: int
CONNECTION_OPEN_OK: int
CONNECTION_CLOSE: int
CONNECTION_CLOSE_OK: int

CHANNEL_OPEN: int
CHANNEL_OPEN_OK: int
CHANNEL_FLOW: int
CHANNEL_FLOW_OK: int
CHANNEL_CLOSE: int
CHANNEL_CLOSE_OK: int

EXCHANGE_DECLARE: int
EXCHANGE_DECLARE_OK: int
EXCHANGE_DELETE: int
EXCHANGE_DELETE_OK: int
EXCHANGE_BIND: int
EXCHANGE_BIND_OK: int
EXCHANGE_UNBIND: int
EXCHANGE_UNBIND_OK: int

QUEUE_DECLARE: int
QUEUE_DECLARE_OK: int
QUEUE_BIND: int
QUEUE_BIND_OK: int
QUEUE_UNBIND: int
QUEUE_UNBIND_OK: int
QUEUE_PURGE: int
QUEUE_PURGE_OK: int
QUEUE_DELETE: int
QUEUE_DELETE_OK: int

BASIC_QOS: int
BASIC_QOS_OK: int
BASIC_CONSUME: int
BASIC_CONSUME_OK: int
BASIC_CANCEL: int
BASIC_CANCEL_OK: int
BASIC_PUBLISH: int
BASIC_RETURN: int
BASIC_DELIVER: int
BASIC_GET: int
BASIC_GET_OK: int
BASIC_GET_EMPTY: int
BASIC_ACK: int
BASIC_REJECT: int
BASIC_RECOVER_ASYNC: int
BASIC_RECOVER: int
BASIC_RECOVER_OK: int
BASIC_NACK: int

TX_SELECT: int
TX_SELECT_OK: int
TX_COMMIT: int
TX_COMMIT_OK: int
TX_ROLLBACK: int
TX_ROLLBACK_OK: int

CONFIRM_SELECT: int
CONFIRM_SELECT_OK: int

MESSAGE_PROPERTIES: tuple[
    str, str, str, str, str, str, str, str, str, str, str, str, str, str
]

FLAG_CONTENT_TYPE: int
FLAG_CONTENT_ENCODING: int
FLAG_HEADERS: int
FLAG_DELIVERY_MODE: int
FLAG_PRIORITY: int
FLAG_CORRELATION_ID: int
FLAG_REPLY_TO: int
FLAG_EXPIRATION: int
FLAG_MESSAGE_ID: int
FLAG_TIMESTAMP: int
FLAG_TYPE: int
FLAG_USER_ID: int
FLAG_APP_ID: int
FLAG_CLUSTER_ID: int
