from datetime import datetime
from typing import Optional
from at_common_schemas.base import BaseSchema
from pydantic import Field
from enum import Enum

# Profile
class StockProfile(BaseSchema):
    """Stock profile information."""
    symbol: str = Field(..., description="The stock symbol.")
    exchange: str = Field(..., description="The stock exchange where the stock is listed.")
    name: str = Field(..., description="The name of the stock.")
    description: str = Field(..., description="A brief description of the stock.")
    currency: str = Field(..., description="The trading currency of the stock (e.g., USD, EUR)")
    country: str = Field(..., description="The country where the stock is based.")
    address: str = Field(..., description="The address of the company's headquarters.")
    sector: str = Field(..., description="The broad market sector classification (e.g., Technology, Healthcare)")
    industry: str = Field(..., description="The specific industry classification within the sector")
    ceo: str = Field(..., description="The name of the company's CEO.")
    ipo_date: datetime = Field(..., description="The date of the company's IPO.")

# Quote
class StockQuote(BaseSchema):
    """Stock quote information."""
    symbol: str = Field(..., description="The stock symbol.")
    price: float = Field(..., description="The current stock price.")
    previous_close: float = Field(..., description="The previous closing price of the stock.")
    change: float = Field(..., description="The change in price from the previous close.")
    change_percentage: float = Field(..., description="The percentage change in price from the previous close.")
    volume: int = Field(..., description="The trading volume of the stock.")
    avg_volume: float = Field(..., description="The average daily trading volume over the last 30 days")
    day_low: float = Field(..., description="The lowest price of the stock for the day.")
    day_high: float = Field(..., description="The highest price of the stock for the day.")
    year_low: float = Field(..., description="The lowest price of the stock over the past year.")
    year_high: float = Field(..., description="The highest price of the stock over the past year.")
    market_cap: float = Field(..., description="Total market value (price × shares outstanding) in the trading currency")
    pe: float = Field(..., description="Price-to-earnings ratio (current price / earnings per share)")
    shares_outstanding: int = Field(..., description="The total number of shares outstanding.")
    timestamp: datetime = Field(..., description="The timestamp of the quote.")

# Candlestick
class StockCandlestick(BaseSchema):
    open: float = Field(..., description="Opening price of the stock")
    high: float = Field(..., description="Highest price of the stock during the period")
    low: float = Field(..., description="Lowest price of the stock during the period")
    close: float = Field(..., description="Closing price of the stock")
    volume: int = Field(..., description="Volume of stocks traded")

class StockCandlestickDaily(StockCandlestick):
    date: datetime = Field(..., description="Date of the stock candlestick")

# Indicators
class StockIndicator(BaseSchema):
    sma5: float = Field(..., description="Simple Moving Average over 5 days")
    sma10: float = Field(..., description="Simple Moving Average over 10 days")
    sma20: float = Field(..., description="Simple Moving Average over 20 days")
    ema5: float = Field(..., description="Exponential Moving Average over 5 days")
    ema10: float = Field(..., description="Exponential Moving Average over 10 days")
    ema20: float = Field(..., description="Exponential Moving Average over 20 days")
    rsi: float = Field(..., description="Relative Strength Index")
    macd: float = Field(..., description="Moving Average Convergence Divergence")
    macd_signal: float = Field(..., description="Signal line for MACD")
    macd_hist: float = Field(..., description="MACD histogram")
    slowk: float = Field(..., description="Stochastic %K")
    slowd: float = Field(..., description="Stochastic %D")
    upper_band: float = Field(..., description="Upper Bollinger Band")
    middle_band: float = Field(..., description="Middle Bollinger Band")
    lower_band: float = Field(..., description="Lower Bollinger Band")
    obv: int = Field(..., description="On-Balance Volume")
    roc: float = Field(..., description="Rate of Change")
    willr: float = Field(..., description="Williams %R")
    atr: float = Field(..., description="Average True Range")
    sig_ma_cross_5_10: int = Field(..., description="Signal for 5-day MA crossing 10-day MA: 1 (5-day crosses above), -1 (5-day crosses below), 0 (no cross)")
    sig_ma_cross_10_20: int = Field(..., description="Signal for 10-20 MA crossover, 1 for cross above, -1 for cross below, 0 for no crossover")
    sig_rsi_overbought: int = Field(..., description="Signal for RSI overbought condition: 1 (RSI > 70), -1 (RSI < 30), 0 (neither)")
    sig_rsi_oversold: int = Field(..., description="Signal for RSI oversold condition, 1 for overbought, -1 for oversold, 0 for no signal")
    sig_macd_crossover: int = Field(..., description="Signal for MACD line crossing signal line: 1 (bullish cross), -1 (bearish cross), 0 (no cross)")
    sig_stoch_crossover: int = Field(..., description="Signal for Stochastic crossover, 1 for crossover, -1 for no crossover, 0 for no signal")
    sig_bb_breakout_up: int = Field(..., description="Signal for Bollinger Band breakout upwards, 1 for breakout, -1 for no breakout, 0 for no signal")
    sig_bb_breakout_down: int = Field(..., description="Signal for Bollinger Band breakout downwards, 1 for breakout, -1 for no breakout, 0 for no signal")
    sig_volume_spike: int = Field(..., description="Signal for volume spike, 1 for spike, -1 for no spike, 0 for no signal")
    sig_higher_high: int = Field(..., description="Signal for higher high, 1 for higher high, -1 for no higher high, 0 for no signal")
    sig_lower_low: int = Field(..., description="Signal for lower low, 1 for lower low, -1 for no lower low, 0 for no signal")

class StockIndicatorDaily(StockIndicator):
    date: datetime = Field(..., description="Date of the stock indicators")

# Financial Period
class StockFinancialPeriod(Enum):
    ANNUAL = "annual"
    QUARTERLY = "quarterly"

# Financial Statements
class StockFinancialStatementCashFlow(BaseSchema):
    date: datetime = Field(..., description="The date of the financial statement.")
    symbol: str = Field(..., description="The stock symbol.")
    reported_currency: str = Field(..., description="The currency in which the financials are reported.")
    cik: str = Field(..., description="The Central Index Key of the company.")
    filling_date: datetime = Field(..., description="The date the statement was filed.")
    accepted_date: datetime = Field(..., description="The date the statement was accepted.")
    calendar_year: str = Field(..., description="The calendar year of the financial statement.")
    period: str = Field(..., description="The reporting period.")
    net_income: Optional[float] = Field(None, description="Net income for the period.")
    depreciation_and_amortization: Optional[float] = Field(None, description="Depreciation and amortization expenses.")
    deferred_income_tax: Optional[float] = Field(None, description="Deferred income tax expenses.")
    stock_based_compensation: Optional[float] = Field(None, description="Stock-based compensation expenses.")
    change_in_working_capital: Optional[float] = Field(None, description="Change in working capital.")
    accounts_receivables: Optional[float] = Field(None, description="Accounts receivables.")
    inventory: Optional[float] = Field(None, description="Inventory value.")
    accounts_payables: Optional[float] = Field(None, description="Accounts payables.")
    other_working_capital: Optional[float] = Field(None, description="Other working capital items.")
    other_non_cash_items: Optional[float] = Field(None, description="Other non-cash items.")
    net_cash_provided_by_operating_activities: Optional[float] = Field(None, description="Net cash provided by operating activities.")
    investments_in_property_plant_and_equipment: Optional[float] = Field(None, description="Investments in property, plant, and equipment.")
    acquisitions_net: Optional[float] = Field(None, description="Net acquisitions.")
    purchases_of_investments: Optional[float] = Field(None, description="Purchases of investments.")
    sales_maturities_of_investments: Optional[float] = Field(None, description="Sales and maturities of investments.")
    other_investing_activites: Optional[float] = Field(None, description="Other investing activities.")
    net_cash_used_for_investing_activites: Optional[float] = Field(None, description="Net cash used for investing activities.")
    debt_repayment: Optional[float] = Field(None, description="Debt repayment amount.")
    common_stock_issued: Optional[float] = Field(None, description="Common stock issued amount.")
    common_stock_repurchased: Optional[float] = Field(None, description="Common stock repurchased amount.")
    dividends_paid: Optional[float] = Field(None, description="Dividends paid amount.")
    other_financing_activites: Optional[float] = Field(None, description="Other financing activities.")
    net_cash_used_provided_by_financing_activities: Optional[float] = Field(None, description="Net cash used or provided by financing activities.")
    effect_of_forex_changes_on_cash: Optional[float] = Field(None, description="Effect of foreign exchange changes on cash.")
    net_change_in_cash: Optional[float] = Field(None, description="Net change in cash during the period.")
    cash_at_end_of_period: Optional[float] = Field(None, description="Cash at the end of the period.")
    cash_at_beginning_of_period: Optional[float] = Field(None, description="Cash at the beginning of the period.")
    operating_cash_flow: Optional[float] = Field(None, description="Operating cash flow.")
    capital_expenditure: Optional[float] = Field(None, description="Capital expenditure amount.")
    free_cash_flow: Optional[float] = Field(None, description="Free cash flow amount.")

class StockFinancialStatementBalanceSheet(BaseSchema):
    date: datetime = Field(..., description="The date of the financial statement.")
    symbol: str = Field(..., description="The stock symbol.")
    reported_currency: str = Field(..., description="The currency in which the financials are reported.")
    cik: str = Field(..., description="The Central Index Key of the company.")
    filling_date: datetime = Field(..., description="The date the statement was filed.")
    accepted_date: datetime = Field(..., description="The date the statement was accepted.")
    calendar_year: str = Field(..., description="The calendar year of the financial statement.")
    period: str = Field(..., description="The reporting period.")
    cash_and_cash_equivalents: Optional[float] = Field(None, description="Cash and cash equivalents.")
    short_term_investments: Optional[float] = Field(None, description="Short-term investments.")
    cash_and_short_term_investments: Optional[float] = Field(None, description="Total cash and short-term investments.")
    net_receivables: Optional[float] = Field(None, description="Net receivables.")
    inventory: Optional[float] = Field(None, description="Inventory value.")
    other_current_assets: Optional[float] = Field(None, description="Other current assets.")
    total_current_assets: Optional[float] = Field(None, description="Total current assets.")
    property_plant_equipment_net: Optional[float] = Field(None, description="Net property, plant, and equipment.")
    goodwill: Optional[float] = Field(None, description="Goodwill amount.")
    intangible_assets: Optional[float] = Field(None, description="Intangible assets amount.")
    goodwill_and_intangible_assets: Optional[float] = Field(None, description="Total goodwill and intangible assets.")
    long_term_investments: Optional[float] = Field(None, description="Long-term investments.")
    tax_assets: Optional[float] = Field(None, description="Tax assets.")
    other_non_current_assets: Optional[float] = Field(None, description="Other non-current assets.")
    total_non_current_assets: Optional[float] = Field(None, description="Total non-current assets.")
    other_assets: Optional[float] = Field(None, description="Other assets.")
    total_assets: Optional[float] = Field(None, description="Total assets.")
    account_payables: Optional[float] = Field(None, description="Accounts payables.")
    short_term_debt: Optional[float] = Field(None, description="Short-term debt amount.")
    tax_payables: Optional[float] = Field(None, description="Tax payables.")
    deferred_revenue: Optional[float] = Field(None, description="Deferred revenue amount.")
    other_current_liabilities: Optional[float] = Field(None, description="Other current liabilities.")
    total_current_liabilities: Optional[float] = Field(None, description="Total current liabilities.")
    long_term_debt: Optional[float] = Field(None, description="Long-term debt amount.")
    deferred_revenue_non_current: Optional[float] = Field(None, description="Deferred revenue (non-current).")
    deferred_tax_liabilities_non_current: Optional[float] = Field(None, description="Deferred tax liabilities (non-current).")
    other_non_current_liabilities: Optional[float] = Field(None, description="Other non-current liabilities.")
    total_non_current_liabilities: Optional[float] = Field(None, description="Total non-current liabilities.")
    other_liabilities: Optional[float] = Field(None, description="Other liabilities.")
    total_liabilities: Optional[float] = Field(None, description="Total liabilities.")
    preferred_stock: Optional[float] = Field(None, description="Preferred stock amount.")
    common_stock: Optional[float] = Field(None, description="Common stock amount.")
    retained_earnings: Optional[float] = Field(None, description="Retained earnings amount.")
    accumulated_other_comprehensive_income_loss: Optional[float] = Field(None, description="Accumulated other comprehensive income/loss.")
    other_total_stockholders_equity: Optional[float] = Field(None, description="Other total stockholders' equity.")
    total_stockholders_equity: Optional[float] = Field(None, description="Total stockholders' equity.")
    total_equity: Optional[float] = Field(None, description="Total equity.")
    total_liabilities_and_stockholders_equity: Optional[float] = Field(None, description="Total liabilities and stockholders' equity.")
    minority_interest: Optional[float] = Field(None, description="Minority interest amount.")
    total_liabilities_and_total_equity: Optional[float] = Field(None, description="Total liabilities and total equity.")
    total_investments: Optional[float] = Field(None, description="Total investments.")
    total_debt: Optional[float] = Field(None, description="Total debt amount.")
    net_debt: Optional[float] = Field(None, description="Net debt amount.")

class StockFinancialStatementIncome(BaseSchema):
    date: datetime = Field(..., description="The date of the financial statement.")
    symbol: str = Field(..., description="The stock symbol.")
    reported_currency: str = Field(..., description="The currency in which the financials are reported.")
    cik: str = Field(..., description="The Central Index Key of the company.")
    filling_date: datetime = Field(..., description="The date the statement was filed.")
    accepted_date: datetime = Field(..., description="The date the statement was accepted.")
    calendar_year: str = Field(..., description="The calendar year of the financial statement.")
    period: str = Field(..., description="The reporting period.")
    revenue: Optional[float] = Field(None, description="Revenue for the period.")
    cost_of_revenue: Optional[float] = Field(None, description="Cost of revenue.")
    gross_profit: Optional[float] = Field(None, description="Gross profit for the period.")
    gross_profit_ratio: Optional[float] = Field(None, description="Gross profit ratio.")
    research_and_development_expenses: Optional[float] = Field(None, description="Research and development expenses.")
    general_and_administrative_expenses: Optional[float] = Field(None, description="General and administrative expenses.")
    selling_and_marketing_expenses: Optional[float] = Field(None, description="Selling and marketing expenses.")
    selling_general_and_administrative_expenses: Optional[float] = Field(None, description="Selling, general and administrative expenses.")
    other_expenses: Optional[float] = Field(None, description="Other expenses.")
    operating_expenses: Optional[float] = Field(None, description="Operating expenses.")
    cost_and_expenses: Optional[float] = Field(None, description="Total costs and expenses.")
    interest_income: Optional[float] = Field(None, description="Interest income.")
    interest_expense: Optional[float] = Field(None, description="Interest expense.")
    depreciation_and_amortization: Optional[float] = Field(None, description="Depreciation and amortization expenses.")
    ebitda: Optional[float] = Field(None, description="Earnings before interest, taxes, depreciation, and amortization.")
    ebitda_ratio: Optional[float] = Field(None, description="EBITDA ratio.")
    operating_income: Optional[float] = Field(None, description="Operating income.")
    operating_income_ratio: Optional[float] = Field(None, description="Operating income ratio.")
    total_other_income_expenses_net: Optional[float] = Field(None, description="Total other income and expenses net.")
    income_before_tax: Optional[float] = Field(None, description="Income before tax.")
    income_before_tax_ratio: Optional[float] = Field(None, description="Income before tax ratio.")
    income_tax_expense: Optional[float] = Field(None, description="Income tax expense.")
    net_income: Optional[float] = Field(None, description="Net income for the period.")
    net_income_ratio: Optional[float] = Field(None, description="Net income ratio.")
    eps: Optional[float] = Field(None, description="Earnings per share.")
    eps_diluted: Optional[float] = Field(None, description="Diluted earnings per share.")
    weighted_average_shs_out: Optional[float] = Field(None, description="Weighted average shares outstanding.")
    weighted_average_shs_out_dil: Optional[float] = Field(None, description="Weighted average shares outstanding (diluted).")

# Financial Analysis Key Metrics & TTM
class StockFinancialAnalysisKeyMetric(BaseSchema):
    symbol: str = Field(..., description="The stock symbol.")
    date: datetime = Field(..., description="The date of the financial metrics.")
    calendar_year: str = Field(..., description="The calendar year of the financial metrics.")
    period: str = Field(..., description="The financial period (e.g., Q1, Q2, etc.).")
    revenue_per_share: Optional[float] = Field(None, description="Revenue per share.")
    net_income_per_share: Optional[float] = Field(None, description="Net income per share.")
    operating_cash_flow_per_share: Optional[float] = Field(None, description="Operating cash flow per share.")
    free_cash_flow_per_share: Optional[float] = Field(None, description="Free cash flow per share.")
    cash_per_share: Optional[float] = Field(None, description="Cash per share.")
    book_value_per_share: Optional[float] = Field(None, description="Book value per share.")
    tangible_book_value_per_share: Optional[float] = Field(None, description="Tangible book value per share.")
    shareholders_equity_per_share: Optional[float] = Field(None, description="Shareholders' equity per share.")
    interest_debt_per_share: Optional[float] = Field(None, description="Interest debt per share.")
    market_cap: Optional[float] = Field(None, description="Market capitalization.")
    enterprise_value: Optional[float] = Field(None, description="Enterprise value.")
    pe_ratio: Optional[float] = Field(None, description="Price-to-earnings ratio.")
    price_to_sales_ratio: Optional[float] = Field(None, description="Price-to-sales ratio.")
    pocf_ratio: Optional[float] = Field(None, description="Price-to-operating cash flow ratio.")
    pfcf_ratio: Optional[float] = Field(None, description="Price-to-free cash flow ratio.")
    pb_ratio: Optional[float] = Field(None, description="Price-to-book ratio.")
    ptb_ratio: Optional[float] = Field(None, description="Price-to-tangible book ratio.")
    ev_to_sales: Optional[float] = Field(None, description="Enterprise value to sales ratio.")
    enterprise_value_over_ebitda: Optional[float] = Field(None, description="Enterprise value over EBITDA.")
    ev_to_operating_cash_flow: Optional[float] = Field(None, description="Enterprise value to operating cash flow ratio.")
    ev_to_free_cash_flow: Optional[float] = Field(None, description="Enterprise value to free cash flow ratio.")
    earnings_yield: Optional[float] = Field(None, description="Earnings yield.")
    free_cash_flow_yield: Optional[float] = Field(None, description="Free cash flow yield.")
    debt_to_equity: Optional[float] = Field(None, description="Debt to equity ratio.")
    debt_to_assets: Optional[float] = Field(None, description="Debt to assets ratio.")
    net_debt_to_ebitda: Optional[float] = Field(None, description="Net debt to EBITDA ratio.")
    current_ratio: Optional[float] = Field(None, description="Current ratio.")
    interest_coverage: Optional[float] = Field(None, description="Interest coverage ratio.")
    income_quality: Optional[float] = Field(None, description="Income quality ratio.")
    dividend_yield: Optional[float] = Field(None, description="Dividend yield.")
    payout_ratio: Optional[float] = Field(None, description="Payout ratio.")
    sales_general_and_administrative_to_revenue: Optional[float] = Field(None, description="SG&A expenses to revenue ratio.")
    research_and_developement_to_revenue: Optional[float] = Field(None, description="R&D expenses to revenue ratio.")
    intangibles_to_total_assets: Optional[float] = Field(None, description="Intangible assets to total assets ratio.")
    capex_to_operating_cash_flow: Optional[float] = Field(None, description="Capital expenditures to operating cash flow ratio.")
    capex_to_revenue: Optional[float] = Field(None, description="Capital expenditures to revenue ratio.")
    capex_to_depreciation: Optional[float] = Field(None, description="Capital expenditures to depreciation ratio.")
    stock_based_compensation_to_revenue: Optional[float] = Field(None, description="Stock-based compensation to revenue ratio.")
    graham_number: Optional[float] = Field(None, description="Graham number.")
    roic: Optional[float] = Field(None, description="Return on invested capital.")
    return_on_tangible_assets: Optional[float] = Field(None, description="Return on tangible assets.")
    graham_net_net: Optional[float] = Field(None, description="Graham net-net value.")
    working_capital: Optional[float] = Field(None, description="Working capital.")
    tangible_asset_value: Optional[float] = Field(None, description="Tangible asset value.")
    net_current_asset_value: Optional[float] = Field(None, description="Net current asset value.")
    invested_capital: Optional[float] = Field(None, description="Invested capital.")
    average_receivables: Optional[float] = Field(None, description="Average receivables.")
    average_payables: Optional[float] = Field(None, description="Average payables.")
    average_inventory: Optional[float] = Field(None, description="Average inventory.")
    days_sales_outstanding: Optional[float] = Field(None, description="Days sales outstanding.")
    days_payables_outstanding: Optional[float] = Field(None, description="Days payables outstanding.")
    days_of_inventory_on_hand: Optional[float] = Field(None, description="Days of inventory on hand.")
    receivables_turnover: Optional[float] = Field(None, description="Receivables turnover ratio.")
    payables_turnover: Optional[float] = Field(None, description="Payables turnover ratio.")
    inventory_turnover: Optional[float] = Field(None, description="Inventory turnover ratio.")
    roe: Optional[float] = Field(None, description="Return on equity.")
    capex_per_share: Optional[float] = Field(None, description="Capital expenditures per share.")

class StockFinancialAnalysisKeyMetricTTM(BaseSchema):
    revenue_per_share_ttm: Optional[float] = Field(None, description="TTM revenue per share.")
    net_income_per_share_ttm: Optional[float] = Field(None, description="TTM net income per share.")
    operating_cash_flow_per_share_ttm: Optional[float] = Field(None, description="TTM operating cash flow per share.")
    free_cash_flow_per_share_ttm: Optional[float] = Field(None, description="TTM free cash flow per share.")
    cash_per_share_ttm: Optional[float] = Field(None, description="TTM cash per share.")
    book_value_per_share_ttm: Optional[float] = Field(None, description="TTM book value per share.")
    tangible_book_value_per_share_ttm: Optional[float] = Field(None, description="TTM tangible book value per share.")
    shareholders_equity_per_share_ttm: Optional[float] = Field(None, description="TTM shareholders' equity per share.")
    interest_debt_per_share_ttm: Optional[float] = Field(None, description="TTM interest debt per share.")
    market_cap_ttm: Optional[float] = Field(None, description="TTM market capitalization.")
    enterprise_value_ttm: Optional[float] = Field(None, description="TTM enterprise value.")
    pe_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-earnings ratio.")
    price_to_sales_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-sales ratio.")
    pocf_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-operating cash flow ratio.")
    pfcf_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-free cash flow ratio.")
    pb_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-book ratio.")
    ptb_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-tangible book ratio.")
    ev_to_sales_ttm: Optional[float] = Field(None, description="TTM enterprise value to sales ratio.")
    enterprise_value_over_ebitda_ttm: Optional[float] = Field(None, description="TTM enterprise value over EBITDA.")
    ev_to_operating_cash_flow_ttm: Optional[float] = Field(None, description="TTM enterprise value to operating cash flow ratio.")
    ev_to_free_cash_flow_ttm: Optional[float] = Field(None, description="TTM enterprise value to free cash flow ratio.")
    earnings_yield_ttm: Optional[float] = Field(None, description="TTM earnings yield.")
    free_cash_flow_yield_ttm: Optional[float] = Field(None, description="TTM free cash flow yield.")
    debt_to_equity_ttm: Optional[float] = Field(None, description="TTM debt to equity ratio.")
    debt_to_assets_ttm: Optional[float] = Field(None, description="TTM debt to assets ratio.")
    net_debt_to_ebitda_ttm: Optional[float] = Field(None, description="TTM net debt to EBITDA ratio.")
    current_ratio_ttm: Optional[float] = Field(None, description="TTM current ratio.")
    interest_coverage_ttm: Optional[float] = Field(None, description="TTM interest coverage ratio.")
    income_quality_ttm: Optional[float] = Field(None, description="TTM income quality ratio.")
    dividend_yield_ttm: Optional[float] = Field(None, description="TTM dividend yield.")
    payout_ratio_ttm: Optional[float] = Field(None, description="TTM payout ratio.")
    sales_general_and_administrative_to_revenue_ttm: Optional[float] = Field(None, description="TTM SG&A expenses to revenue ratio.")
    research_and_developement_to_revenue_ttm: Optional[float] = Field(None, description="TTM R&D expenses to revenue ratio.")
    intangibles_to_total_assets_ttm: Optional[float] = Field(None, description="TTM intangible assets to total assets ratio.")
    capex_to_operating_cash_flow_ttm: Optional[float] = Field(None, description="TTM capital expenditures to operating cash flow ratio.")
    capex_to_revenue_ttm: Optional[float] = Field(None, description="TTM capital expenditures to revenue ratio.")
    capex_to_depreciation_ttm: Optional[float] = Field(None, description="TTM capital expenditures to depreciation ratio.")
    stock_based_compensation_to_revenue_ttm: Optional[float] = Field(None, description="TTM stock-based compensation to revenue ratio.")
    graham_number_ttm: Optional[float] = Field(None, description="TTM Graham number.")
    roic_ttm: Optional[float] = Field(None, description="TTM return on invested capital.")
    return_on_tangible_assets_ttm: Optional[float] = Field(None, description="TTM return on tangible assets.")
    graham_net_net_ttm: Optional[float] = Field(None, description="TTM Graham net-net value.")
    working_capital_ttm: Optional[float] = Field(None, description="TTM working capital.")
    tangible_asset_value_ttm: Optional[float] = Field(None, description="TTM tangible asset value.")
    net_current_asset_value_ttm: Optional[float] = Field(None, description="TTM net current asset value.")
    invested_capital_ttm: Optional[float] = Field(None, description="TTM invested capital.")
    average_receivables_ttm: Optional[float] = Field(None, description="TTM average receivables.")
    average_payables_ttm: Optional[float] = Field(None, description="TTM average payables.")
    average_inventory_ttm: Optional[float] = Field(None, description="TTM average inventory.")
    days_sales_outstanding_ttm: Optional[float] = Field(None, description="TTM days sales outstanding.")
    days_payables_outstanding_ttm: Optional[float] = Field(None, description="TTM days payables outstanding.")
    days_of_inventory_on_hand_ttm: Optional[float] = Field(None, description="TTM days of inventory on hand.")
    receivables_turnover_ttm: Optional[float] = Field(None, description="TTM receivables turnover ratio.")
    payables_turnover_ttm: Optional[float] = Field(None, description="TTM payables turnover ratio.")
    inventory_turnover_ttm: Optional[float] = Field(None, description="TTM inventory turnover ratio.")
    roe_ttm: Optional[float] = Field(None, description="TTM return on equity.")
    capex_per_share_ttm: Optional[float] = Field(None, description="TTM capital expenditures per share.")
    dividend_per_share_ttm: Optional[float] = Field(None, description="TTM dividend per share.")
    debt_to_market_cap_ttm: Optional[float] = Field(None, description="TTM debt to market capitalization ratio.")

# Financial Analysis Ratios and TTM
class StockFinancialAnalysisRatio(BaseSchema):
    symbol: str = Field(..., description="The stock symbol.")
    date: datetime = Field(..., description="The date of the financial ratios.")
    calendar_year: str = Field(..., description="The calendar year of the financial ratios.")
    period: str = Field(..., description="The financial period (e.g., Q1, Q2, etc.).")
    current_ratio: Optional[float] = Field(None, description="Current ratio.")
    quick_ratio: Optional[float] = Field(None, description="Quick ratio.")
    cash_ratio: Optional[float] = Field(None, description="Cash ratio.")
    days_of_sales_outstanding: Optional[float] = Field(None, description="Days of sales outstanding.")
    days_of_inventory_outstanding: Optional[float] = Field(None, description="Days of inventory outstanding.")
    operating_cycle: Optional[float] = Field(None, description="Operating cycle.")
    days_of_payables_outstanding: Optional[float] = Field(None, description="Days of payables outstanding.")
    cash_conversion_cycle: Optional[float] = Field(None, description="Cash conversion cycle.")
    gross_profit_margin: Optional[float] = Field(None, description="Gross profit margin.")
    operating_profit_margin: Optional[float] = Field(None, description="Operating profit margin.")
    pretax_profit_margin: Optional[float] = Field(None, description="Pretax profit margin.")
    net_profit_margin: Optional[float] = Field(None, description="Net profit margin.")
    effective_tax_rate: Optional[float] = Field(None, description="Effective tax rate.")
    return_on_assets: Optional[float] = Field(None, description="Return on assets.")
    return_on_equity: Optional[float] = Field(None, description="Return on equity.")
    return_on_capital_employed: Optional[float] = Field(None, description="Return on capital employed.")
    net_income_per_ebt: Optional[float] = Field(None, description="Net income per EBIT.")
    ebt_per_ebit: Optional[float] = Field(None, description="EBT per EBIT.")
    ebit_per_revenue: Optional[float] = Field(None, description="EBIT per revenue.")
    debt_ratio: Optional[float] = Field(None, description="Debt ratio.")
    debt_equity_ratio: Optional[float] = Field(None, description="Debt to equity ratio.")
    long_term_debt_to_capitalization: Optional[float] = Field(None, description="Long-term debt to capitalization ratio.")
    total_debt_to_capitalization: Optional[float] = Field(None, description="Total debt to capitalization ratio.")
    interest_coverage: Optional[float] = Field(None, description="Interest coverage ratio.")
    cash_flow_to_debt_ratio: Optional[float] = Field(None, description="Cash flow to debt ratio.")
    company_equity_multiplier: Optional[float] = Field(None, description="Company equity multiplier.")
    receivables_turnover: Optional[float] = Field(None, description="Receivables turnover ratio.")
    payables_turnover: Optional[float] = Field(None, description="Payables turnover ratio.")
    inventory_turnover: Optional[float] = Field(None, description="Inventory turnover ratio.")
    fixed_asset_turnover: Optional[float] = Field(None, description="Fixed asset turnover ratio.")
    asset_turnover: Optional[float] = Field(None, description="Asset turnover ratio.")
    operating_cash_flow_per_share: Optional[float] = Field(None, description="Operating cash flow per share.")
    free_cash_flow_per_share: Optional[float] = Field(None, description="Free cash flow per share.")
    cash_per_share: Optional[float] = Field(None, description="Cash per share.")
    payout_ratio: Optional[float] = Field(None, description="Payout ratio.")
    operating_cash_flow_sales_ratio: Optional[float] = Field(None, description="Operating cash flow to sales ratio.")
    free_cash_flow_operating_cash_flow_ratio: Optional[float] = Field(None, description="Free cash flow to operating cash flow ratio.")
    cash_flow_coverage_ratios: Optional[float] = Field(None, description="Cash flow coverage ratios.")
    short_term_coverage_ratios: Optional[float] = Field(None, description="Short-term coverage ratios.")
    capital_expenditure_coverage_ratio: Optional[float] = Field(None, description="Capital expenditure coverage ratio.")
    dividend_paid_and_capex_coverage_ratio: Optional[float] = Field(None, description="Dividend paid and capital expenditure coverage ratio.")
    dividend_payout_ratio: Optional[float] = Field(None, description="Dividend payout ratio.")
    price_book_value_ratio: Optional[float] = Field(None, description="Price to book value ratio.")
    price_to_book_ratio: Optional[float] = Field(None, description="Price to book ratio.")
    price_to_sales_ratio: Optional[float] = Field(None, description="Price to sales ratio.")
    price_earnings_ratio: Optional[float] = Field(None, description="Price to earnings ratio.")
    price_to_free_cash_flows_ratio: Optional[float] = Field(None, description="Price to free cash flows ratio.")
    price_to_operating_cash_flows_ratio: Optional[float] = Field(None, description="Price to operating cash flows ratio.")
    price_cash_flow_ratio: Optional[float] = Field(None, description="Price cash flow ratio.")
    price_earnings_to_growth_ratio: Optional[float] = Field(None, description="Price earnings to growth ratio.")
    price_sales_ratio: Optional[float] = Field(None, description="Price sales ratio.")
    dividend_yield: Optional[float] = Field(None, description="Dividend yield.")
    enterprise_value_multiple: Optional[float] = Field(None, description="Enterprise value multiple.")
    price_fair_value: Optional[float] = Field(None, description="Price fair value.")

class StockFinancialAnalysisRatioTTM(BaseSchema):
    dividend_yield_ttm: Optional[float] = Field(None, description="TTM dividend yield.")
    dividend_yield_percentage_ttm: Optional[float] = Field(None, description="TTM dividend yield percentage.")
    pe_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-earnings ratio.")
    peg_ratio_ttm: Optional[float] = Field(None, description="TTM price-to-earnings to growth ratio.")
    payout_ratio_ttm: Optional[float] = Field(None, description="TTM payout ratio.")
    current_ratio_ttm: Optional[float] = Field(None, description="TTM current ratio.")
    quick_ratio_ttm: Optional[float] = Field(None, description="TTM quick ratio.")
    cash_ratio_ttm: Optional[float] = Field(None, description="TTM cash ratio.")
    days_of_sales_outstanding_ttm: Optional[float] = Field(None, description="TTM days of sales outstanding.")
    days_of_inventory_outstanding_ttm: Optional[float] = Field(None, description="TTM days of inventory outstanding.")
    operating_cycle_ttm: Optional[float] = Field(None, description="TTM operating cycle.")
    days_of_payables_outstanding_ttm: Optional[float] = Field(None, description="TTM days of payables outstanding.")
    cash_conversion_cycle_ttm: Optional[float] = Field(None, description="TTM cash conversion cycle.")
    gross_profit_margin_ttm: Optional[float] = Field(None, description="TTM gross profit margin.")
    operating_profit_margin_ttm: Optional[float] = Field(None, description="TTM operating profit margin.")
    pretax_profit_margin_ttm: Optional[float] = Field(None, description="TTM pretax profit margin.")
    net_profit_margin_ttm: Optional[float] = Field(None, description="TTM net profit margin.")
    effective_tax_rate_ttm: Optional[float] = Field(None, description="TTM effective tax rate.")
    return_on_assets_ttm: Optional[float] = Field(None, description="TTM return on assets.")
    return_on_equity_ttm: Optional[float] = Field(None, description="TTM return on equity.")
    return_on_capital_employed_ttm: Optional[float] = Field(None, description="TTM return on capital employed.")
    net_income_per_ebt_ttm: Optional[float] = Field(None, description="TTM net income per EBIT.")
    ebt_per_ebit_ttm: Optional[float] = Field(None, description="TTM EBT per EBIT.")
    ebit_per_revenue_ttm: Optional[float] = Field(None, description="TTM EBIT per revenue.")
    debt_ratio_ttm: Optional[float] = Field(None, description="TTM debt ratio.")
    long_term_debt_to_capitalization_ttm: Optional[float] = Field(None, description="TTM long-term debt to capitalization ratio.")
    total_debt_to_capitalization_ttm: Optional[float] = Field(None, description="TTM total debt to capitalization ratio.")
    interest_coverage_ttm: Optional[float] = Field(None, description="TTM interest coverage ratio.")
    cash_flow_to_debt_ratio_ttm: Optional[float] = Field(None, description="TTM cash flow to debt ratio.")
    company_equity_multiplier_ttm: Optional[float] = Field(None, description="TTM company equity multiplier.")
    receivables_turnover_ttm: Optional[float] = Field(None, description="TTM receivables turnover ratio.")
    payables_turnover_ttm: Optional[float] = Field(None, description="TTM payables turnover ratio.")
    inventory_turnover_ttm: Optional[float] = Field(None, description="TTM inventory turnover ratio.")
    fixed_asset_turnover_ttm: Optional[float] = Field(None, description="TTM fixed asset turnover ratio.")
    asset_turnover_ttm: Optional[float] = Field(None, description="TTM asset turnover ratio.")
    operating_cash_flow_per_share_ttm: Optional[float] = Field(None, description="TTM operating cash flow per share.")
    free_cash_flow_per_share_ttm: Optional[float] = Field(None, description="TTM free cash flow per share.")
    cash_per_share_ttm: Optional[float] = Field(None, description="TTM cash per share.")
    operating_cash_flow_sales_ratio_ttm: Optional[float] = Field(None, description="TTM operating cash flow to sales ratio.")
    free_cash_flow_operating_cash_flow_ratio_ttm: Optional[float] = Field(None, description="TTM free cash flow to operating cash flow ratio.")
    cash_flow_coverage_ratios_ttm: Optional[float] = Field(None, description="TTM cash flow coverage ratios.")
    short_term_coverage_ratios_ttm: Optional[float] = Field(None, description="TTM short-term coverage ratios.")
    capital_expenditure_coverage_ratio_ttm: Optional[float] = Field(None, description="TTM capital expenditure coverage ratio.")
    dividend_paid_and_capex_coverage_ratio_ttm: Optional[float] = Field(None, description="TTM dividend paid and capital expenditure coverage ratio.")
    price_book_value_ratio_ttm: Optional[float] = Field(None, description="TTM price to book value ratio.")
    price_to_book_ratio_ttm: Optional[float] = Field(None, description="TTM price to book ratio.")
    price_to_sales_ratio_ttm: Optional[float] = Field(None, description="TTM price to sales ratio.")
    price_earnings_ratio_ttm: Optional[float] = Field(None, description="TTM price to earnings ratio.")
    price_to_free_cash_flows_ratio_ttm: Optional[float] = Field(None, description="TTM price to free cash flows ratio.")
    price_to_operating_cash_flows_ratio_ttm: Optional[float] = Field(None, description="TTM price to operating cash flows ratio.")
    price_cash_flow_ratio_ttm: Optional[float] = Field(None, description="TTM price cash flow ratio.")
    price_earnings_to_growth_ratio_ttm: Optional[float] = Field(None, description="TTM price earnings to growth ratio.")
    price_sales_ratio_ttm: Optional[float] = Field(None, description="TTM price sales ratio.")
    enterprise_value_multiple_ttm: Optional[float] = Field(None, description="TTM enterprise value multiple.")
    price_fair_value_ttm: Optional[float] = Field(None, description="TTM price fair value.")
    dividend_per_share_ttm: Optional[float] = Field(None, description="TTM dividend per share.")

class StockFilingForm(Enum):
    FORM_20F = "20-F"
    FORM_6K = "6-K"
    FORM_10K = "10-K"
    FORM_10Q = "10-Q"
    FORM_8K = "8-K"
    FORM_5 = "5"
    FORM_4 = "4"
    FORM_3 = "3"

class StockFilingMeta(BaseSchema):
    accession_number: str = Field(..., description="Accession number of the filing")
    form: StockFilingForm = Field(..., description="Form of the filing")
    filing_date: datetime = Field(..., description="Filing date of the filing")
    acceptance_datetime: datetime = Field(..., description="Acceptance datetime of the filing")

class StockFilingDocument(BaseSchema):
    meta: StockFilingMeta = Field(..., description="Meta information of the filing")
    content: str = Field(..., description="Content of the filing")