
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-09T20:06:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "db9e3c18c91f82b8eadd1e07d4ee840072c93d0b",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
