from _typeshed import Incomplete
from onbbu.logger import LogLevel as LogLevel, logger as logger

class DatabaseManager:
    database_url: Incomplete
    model_modules: list[str]
    INSTALLED_APPS: Incomplete
    def __init__(self, database_url: str, INSTALLED_APPS: list[str]) -> None: ...
    async def load_models(self) -> None: ...
    def get_config(self): ...
    command: Incomplete
    async def init(self) -> None: ...
    async def migrate(self) -> None: ...
    async def upgrade(self) -> None: ...
    async def downgrade(self, steps: int = 1) -> None: ...
    async def history(self) -> None: ...
    async def create_database(self) -> None: ...
    async def drop_database(self) -> None: ...
    async def reset_database(self) -> None: ...
    async def show_status(self) -> None: ...
    async def apply_all_migrations(self) -> None: ...
    async def rollback_all_migrations(self) -> None: ...
    async def seed_data(self) -> None: ...
    async def close(self) -> None: ...
