from .TagInspector import TagInspector
from .TrustedPrefixesTagInspector import TrustedPrefixesTagInspector
from .UnTrustedTagInspector import UnTrustedTagInspector
from .TrustedTagInspector import TrustedTagInspector