# Generated by Django 3.2 on 2025-03-07 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=10, verbose_name='Acción')),
                ('app_label', models.CharField(max_length=255, verbose_name='App')),
                ('model_name', models.CharField(max_length=255, verbose_name='Modelo')),
                ('objeto_id', models.CharField(max_length=255, verbose_name='ID del Objeto')),
                ('dato_anterior', models.JSONField(blank=True, null=True, verbose_name='Dato Anterior')),
                ('dato_nuevo', models.JSONField(blank=True, null=True, verbose_name='Dato Nuevo')),
                ('navegador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
