from ansys.mapdl.core import launch_mapdl

mapdl = launch_mapdl()

mapdl.prep7()
mapdl.mp('EX', 1, 10e3)
mapdl.mp('EX', 2, 100e3)
mapdl.et(1, '188')
mapdl.et(2, '180')
mapdl.sectype(1, 'beam', 'rect')
mapdl.secdata(120, 100)
mapdl.sectype(2, 'link')
mapdl.secdata(280)
mapdl.seccontrol(0, 1)
mapdl.n(1, 0, 0, 0)
mapdl.n(2, -1000, 0, 0)
mapdl.n(3, 0, 0, 1000)
mapdl.secnum(1)
mapdl.mat(1)
mapdl.type(1)
mapdl.e(1, 2, 3)
mapdl.mat(2)
mapdl.secnum(2)
mapdl.type(2)
mapdl.e(1, 3)
mapdl.nsel('s', 'node', "", 2, 3)
mapdl.d("all", "ux")
mapdl.d("all", "uy")
mapdl.d("all", "uz")
mapdl.d("all", "rotx")
mapdl.d("all", "rotz")
mapdl.sfbeam(1, 1, 'pres', 10000)
mapdl.inistate('DEFINE', 2, 'all', 'all', 'all', 2000)
mapdl.solution()
mapdl.allsel()
mapdl.antype(0)
mapdl.nsubst(1)
mapdl.time(1)
mapdl.solve()
mapdl.finish()
mapdl.post1()
mapdl.set(1, 1)
ff = mapdl.prnsol('u', 'sum')
gg = mapdl.presol('smisc', '1')
print(gg.to_list())
mapdl.exit()
