
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-07T17:30:07-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "da6c058b93ef649817ef9638e12212c3c4def5be",
 "version": "2.56.2rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
