default_config = {
    "batch_cooldown_size": 1,
    "batch_cooldown_time": 30,
    "clear_vote": False,
    "edit_only": False,
    "hours": 24,
    "item": "overview",
    "keep_a_copy": False,
    "max_score": 100,
    "multi_blacklist": [],
    "multi_whitelist": [],
    "nuke_hours": None,
    "password": None,
    "replacement_format": "random",
    "save_directory": "/tmp",
    "sort": "new",
    "trial_run": False,
    "username": None,
    "verbose": True,
    "whitelist_distinguished": True,
    "whitelist_gilded": True,
    "whitelist_ids": [],
    "whitelist": [],
}
