# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nillion/membership/v1/version.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class NodeVersion(betterproto.Message):
    """The node's version."""

    version: "SemverVersion" = betterproto.message_field(1)
    """The node's version."""

    git_hash: str = betterproto.string_field(2)
    """The built git commit hash."""


@dataclass(eq=False, repr=False)
class SemverVersion(betterproto.Message):
    """A semver version."""

    major: int = betterproto.uint64_field(1)
    """The major version."""

    minor: int = betterproto.uint64_field(2)
    """The minor version."""

    patch: int = betterproto.uint64_field(3)
    """The patch version."""

    pre_release: str = betterproto.string_field(4)
    """The optional pre-release version."""
