
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-10T11:19:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ae886b93a233ada6c1ab16935e2cd54098e3853",
 "version": "1.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
