
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-02T22:03:20+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "b3b850ad906d1dbd36d3b6338d20a00bb11dadc8",
 "version": "0+untagged.4.gb3b850a.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
