key_to_comp = {
  'src/apps/enojs/pdf-demo.js': True,
  'src/apps/enojs/t.js': True,
  'src/apps/enojs/more/time-record.js': True,
  'src/apps/enojs/more/eno-prototype/foo/index.js': True,
  'src/apps/enojs/more/evo/map.js': True,
  'src/apps/enojs/more/evo/res/universe/index.js': True,
  'src/apps/enojs/archived/eno-demo.js': True,
  'src/apps/enojs/lit/dashboard.js': True,
  'src/apps/enojs/lit/src/inputs/books.js': True,
  'src/apps/enojs/lit/src/inputs/index.js': True,
  'src/apps/enojs/lit/science/src/astronomy/units.js': True,
  'src/apps/enojs/lit/science/src/astronomy/index.js': True,
  'src/apps/enojs/lit/science/src/astronomy/data-universe.js': True,
  'src/apps/enojs/lit/science/src/astronomy/data-solar-system.js': True,
  'src/apps/enojs/lit/science/src/main/smooth-zoom.js': True,
  'src/apps/enojs/lit/science/src/main/units.js': True,
  'src/apps/enojs/proj/stome/frontend/storage.js': True,
  'src/apps/enojs/proj/stome/frontend/api.js': True,
  'src/apps/enojs/proj/stome/frontend/index.js': True,
  'src/apps/enojs/proj/quantix/frontend/deposit.js': True,
  'src/apps/enojs/proj/quantix/frontend/btc-aip.js': True,
  'src/apps/enojs/proj/quantix/frontend/fund/sync.js': True,
  'src/apps/enojs/proj/quantix/frontend/fund/details/index.js': True,
  'src/apps/enojs/proj/quantix/frontend/backtesting/index.js': True,
  'src/apps/enojs/proj/quantix/frontend/dashboard/pe.js': True,
  'src/apps/enojs/proj/quantix/info/aws/index.js': True,
}
