# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nillion/values/v1/delete.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class DeleteValuesRequest(betterproto.Message):
    """A request to delete a previously stored set of values."""

    values_id: bytes = betterproto.bytes_field(1)
    """The identifier of the values entity to be deleted."""
