# Generated by Django 4.2.1 on 2023-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0005_alter_apiuser_id_alter_externalwebhook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='validation_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formfieldtemplate',
            name='validation_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
