# Generated by Django 4.2.1 on 2023-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0006_formfield_validation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='default_value',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldtemplate',
            name='default_value',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
