# Generated by Django 4.2.1 on 2023-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0007_alter_formfield_default_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldtemplate',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=511, null=True),
        ),
    ]
