# Generated by Django 4.2.1 on 2023-11-21 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apollo', '0008_alter_formfield_label_alter_formfieldtemplate_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
