#!/usr/bin/env bash

set -eux

uv publish --username=__token__ --password=pypi-AgEIcHlwaS5vcmcCJGE2ZjVjZmFmLWMwYjItNDA0OC1hZWQyLTdjMjIyYmJlNzJlMgACDlsxLFsid3VqaW5nIl1dAAIsWzIsWyI0NGUwY2QxNC00ODM0LTQzN2MtYTkyNi1kZjNjYTk3OGEyNzUiXV0AAAYg3bKB8OQrrwlW5W0SjMf1AHEfffHx97hZN0LV9P1vZ0M