# Generated by Django 3.2.12 on 2022-03-13 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.PAYMENT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEPAMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=64, verbose_name='Account holder')),
                ('iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN of bank account')),
                ('bic', localflavor.generic.models.BICField(max_length=11, verbose_name='BIC/SWIFT code of bank')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date mandate was granted')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sepa_mandate', to=settings.PAYMENT_MODEL)),
            ],
        ),
    ]
