# Generated by Django 4.2.6 on 2025-02-20 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IpEncryptionKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dtm", models.DateTimeField(auto_now_add=True)),
                ("updated_dtm", models.DateTimeField(auto_now=True)),
                (
                    "ip_address_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.GenericIPAddressField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("secrets", models.TextField()),
                ("partner_code", models.CharField(max_length=100, unique=True)),
                ("valid_till", models.DateTimeField(null=True)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
