from enum import Enum


class Exchange(Enum):
    BINANCE = "Binance"
    BINANCE_COINM = "BinanceCoinm"
    BINANCE_USDM = "BinanceUsdm"
    BITGET = "Bitget"
    BITMEX = "Bitmex"
    BITUNIX = "Bitunix"
    BYBIT = "Bybit"
    COINBASE = "Coinbase"
    DERIBIT = "Deribit"
    GATEIO = "GateIO"
    GEMINI = "Gemini"
    HUOBI = "Huobi"
    HYPERLIQUID = "Hyperliquid"
    KRAKEN = "Kraken"
    KUCOIN = "Kucoin"
    KUCOIN_FUTURES = "KucoinFutures"
    OKX = "Okx"
    PHEMEX = "Phemex"
    UPBIT = "Upbit"
    WOO = "Woo"
    MEXC = "Mexc"
    LBANK = "LBank"
