
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-06T18:20:48+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "cd8d57dfdf19f1acf8220d70fee3c4015371184d",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
