
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-08T13:51:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "67d6d79138975614a8336efce4e15a6a915ec138",
 "version": "v1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
