# Stub file for type hints

import functools
import inspect
from functools import wraps
from pywxbase.message.event import EventBus

EVENT_BUS: EventBus: ...
def register_event_bus(cls): ...
def new_init(self, *args, **kwargs): ...
def on_event(event_name, once=False): ...
def decorator(func): ...
def wrapper(*args, **kwargs): ...
