# Stub file for type hints

import inspect
import threading
import asyncio
import types
import weakref
from concurrent.futures import ThreadPoolExecutor
from collections import defaultdict
from typing import Callable

class EventBus:
    def __init__(self, *args, **kwargs): ...
    def _wrap_handler(self, *args, **kwargs): ...
    def subscribe(self, *args, **kwargs): ...
    def subscribe_once(self, *args, **kwargs): ...
    def unsubscribe(self, *args, **kwargs): ...
    def _run_handler(self, *args, **kwargs): ...
    def publish(self, *args, **kwargs): ...
    def clear_event(self, *args, **kwargs): ...
    def clear_all(self, *args, **kwargs): ...
    def shutdown(self, *args, **kwargs): ...

