# Generated by Django 4.2.6 on 2024-12-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_meta_og', '0002_default_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMetaOg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'en')], max_length=20)),
                ('meta', models.ManyToManyField(to='django_meta_og.content')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'unique_together': {('language', 'page')},
            },
        ),
    ]
