#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['kqhivemind_hivebox']

package_data = \
{'': ['*'], 'kqhivemind_hivebox': ['dist/*']}

install_requires = \
['gpiod==2.2.1',
 'nfcpy==1.0.3',
 'requests==2.31.0',
 'py532lib==2018.6.14.dev1',
 'websocket-client==1.2.1']

entry_points = \
{'console_scripts': ['hivebox = kqhivemind_hivebox:main']}

setup(name='kqhivemind_hivebox',
      version='1.1.5',
      description='HiveMind NFC reader client for HiveBox',
      author=None,
      author_email='KQHiveMind <contact@kqhivemind.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
