def auth(auth_method: str, profile_name: str, access_key_id: str, secret_access_key: str, sso_url: str, sso_role_name: str, sso_account_id: str): ...
def crawler(session, accounts_list_src: str, accounts: str, ou: str, statuses: str) -> list: ...
def main() -> None: ...
